spark.sql.adaptive.enabled             true
spark.sql.execution.pyarrow.enabled    true
spark.dynamicAllocation.enabled        true
spark.rdd.compress                     true
spark.shuffle.service.enabled          true
spark.shuffle.compress                 true
spark.shuffle.spill.compress           true

spark.sql.sources.partitionOverwriteMode dynamic
spark.serializer                         org.apache.spark.serializer.KryoSerializer
spark.storage.level                      MEMORY_AND_DISK_SER

spark.eventLog.enabled        true
spark.eventLog.dir            file:/opt/spark/logs/events
spark.history.fs.logDirectory file:/opt/spark/logs/events
spark.history.provider        org.apache.spark.deploy.history.FsHistoryProvider

# AWS Config
spark.hadoop.fs.s3a.path.style.access        true
spark.hadoop.fs.s3a.fast.upload              true
spark.hadoop.fs.s3a.aws.credentials.provider org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider
spark.hadoop.fs.s3a.impl                     org.apache.hadoop.fs.s3a.S3AFileSystem
spark.hadoop.fs.s3a.multipart.size           104857600